---
language: python
python: "2.7"

sudo: required

services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install setuptools==32.3.1
  - pip install docker-py==1.10.6

  # Check ansible version
  - ansible --version
  # Check docker-py version
  - pip show docker-py

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhost_key_checking = False' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/hosts.ini --syntax-check --limit travis --connection=local
  - ansible-playbook tests/test.yml -i tests/hosts.ini --check --limit travis --connection=local
  - ansible-playbook -i tests/hosts.ini tests/test.yml --limit travis --connection=local
  - >
    ansible-playbook -i tests/hosts.ini tests/test.yml --limit travis --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/